/*
 * This file is auto-generated by `contour_parse.py` (from this repo)
 */

#pragma once
#include "math.hpp"

struct SpiritData {
    const wchar_t* filename;
    const ObjectContour contour;
    const float scale;
};

struct Spirits {
    SpiritData controller {
        .filename = L"assets/rocket.png",
        .contour = {
            .vertices = {
                { -0.3f, -52.5f },
                { -10.8f, -40.8f },
                { -16.2f, -28.2f },
                { -18.3f, -13.5f },
                { -17.7f, 2.7f },
                { -24.9f, 17.7f },
                { -23.1f, 37.5f },
                { 22.2f, 38.4f },
                { 25.2f, 17.1f },
                { 17.1f, 5.4f },
                { 18.0f, -15.9f },
                { 15.6f, -28.5f },
                { 9.9f, -42.3f },
            },
            .half_of_sides = { 50.4f, 105.3f },
        },
        .scale = 0.3f,
    };

    SpiritData asteroid {
        .filename = L"assets/asteroid_small.png",
        .contour = {
            .vertices = {
                { -28.2f, -35.45f },
                { 15.6f, -40.85f },
                { 37.8f, -23.65f },
                { 39.0f, -3.85f },
                { 44.0f, 8.15f },
                { 31.0f, 37.35f },
                { -11.2f, 38.75f },
                { -29.6f, 29.75f },
                { -45.4f, -2.25f },
            },
            .half_of_sides = { 50.0f, 43.85f },
        },
        .scale = 0.1f,
    };

    SpiritData bullet {
        .filename = L"assets/bullet.png",
        .contour = {
            .vertices = {
                { 0.5f, -54.12f },
                { 4.25f, -42.62f },
                { 5.0f, -17.62f },
                { -2.75f, -17.62f },
                { -2.25f, -42.62f },
            },
            .half_of_sides = { 12.75f, 71.38f },
        },
        .scale = 0.25f,
    };

};
